config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
  resources :bookmarks, only: [:new, :create]
end
resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Movies Lists</h1>
<% @lists.each do |list| %>
<li><%= link_to list.name, list_path(list) %></li>
<% end %>


<p><%= link_to "create a movie list", new_list_path %></p>

app/views/lists/new.html.erb
<h1>Create a movie list</h1>

<%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<h3> <% @list.movies.each do |movie| %></h1>
<p> <%= movie.title %> </p>
  <p><%= movie.overview %></p>
  <p> <% bookmark = Bookmark.find_by(movie: movie, list: @list)%> </p>
  <p> <%= bookmark.comment %> <%= link_to "delete",
                    bookmark_path(bookmark),
                    method: :delete,
                    data: { confirm: "Are you sure you want to remove it"}%></p>
<% end %>

<%= simple_form_for([ @list, @bookmark ]) do |f| %>
<%= f.input :comment, label:"bookmark" %>
<%= f.association :movie, prompt: 'Select a movie' %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

<p><%= link_to "Lists", lists_path %></p>